# -*- coding: utf-8 -*-
"""Assignment_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZ3vwjeoJi--jVamM0JzsEUqCC9jNc19
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
data=pd.read_csv("/content/exams.csv")

data

data.isna().sum()

data["gender"].mode()

data["gender"].fillna("male",inplace=True)

math=data["math score"].mean()
read=data["reading score"].mean()
write=data["writing score"].mean()
data["math score"].fillna(math,inplace=True)
data["reading score"].fillna(read,inplace=True)
data["writing score"].fillna(write,inplace=True)

data.isna().sum()

data

le=LabelEncoder()
data["gender"]=le.fit_transform(data["gender"])
data["race/ethnicity"]=le.fit_transform(data["race/ethnicity"])
data["parental level of education"]=le.fit_transform(data["parental level of education"])
data["lunch"]=le.fit_transform(data["lunch"])
data["test preparation course"]=le.fit_transform(data["test preparation course"])

data

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import  train_test_split
from sklearn.metrics import accuracy_score
X=data.drop(columns=["writing score"])
y=data["writing score"]

X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.25)

model=LinearRegression()

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

y_pred

y_test

from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

from sklearn.metrics import r2_score
r2_score_value = r2_score(y_test, y_pred)
print("R-squared:", r2_score_value)

"""the model is very much accurate to the scores"""

